services:
  matchma-server:
    build: .
    # command: ["/matchma", "--prod"] # uncomment this if production enviroment
    command: ["/matchma", "--testing", "--player-count=200"]
    depends_on:
      matchma-db:
        condition: service_healthy
    environment:
      JWT-Secret: "Production_test_here_i_come" # Change this if production!
      DB-Conn: "matchma:1234@tcp(matchma-db:3306)/Matchma" # Change this if production!
    ports:
      - "8080:8080"
    links:
      - "matchma-db"

  matchma-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "1234" # Change this if production!
      MYSQL_DATABASE: "Matchma"
      MYSQL_USER: "matchma"
      MYSQL_PASSWORD: "1234" # Change this if production!
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
